services:
  - type: web
    name: soko-api
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_DAYS
        value: "30"
      - key: DARAJA_CONSUMER_KEY
        sync: false
      - key: DARAJA_CONSUMER_SECRET
        sync: false
      - key: DARAJA_BASE_URL
        value: https://api.safaricom.co.ke
      - key: DARAJA_SHORTCODE
        sync: false
      - key: DARAJA_PASSKEY
        sync: false
      - key: API_PUBLIC_URL
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    autoDeploy: true